FROM node:22-slim

RUN apt-get update -y && apt-get install -y openssl && \
  apt-get clean && rm -rf /var/lib/apt/lists/* && \
  npm install -g npm@^11

WORKDIR /app

COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY . .

RUN npm run db:generate && npm run build

CMD ["sleep", "infinity"]
